version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leave-amp-api
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Mount for development (comment out for production)
      - ./app:/app/app:ro
    networks:
      - leave-amp-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:${PORT:-8000}/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  leave-amp-network:
    driver: bridge

